Repository swapagarwal/swag-for-dev, pull requests merged in 2018-12, with the labels that each got.

#190 chore(licence) update package.json licence field
  site/package.json
Labels: bug

#170 Short-circuit cachebust for development
  .gitignore
  gulpfile.js
  netlify.toml
  package-lock.json
  package.json
Labels: bug, urgent

#161 Add added date for each swag item
  data.json
Labels: enhancement

#189 feat(lint) use xo linter
  .editorconfig
  .eslintrc
  get-data.js
  gulpfile.js
  package-lock.json
  package.json
  src/js/index.js
Labels: enhancement

#204 added pointer-events none to arrow in select-wrapper
  src/styl/index.styl
Labels: :bug: bug

#165 Remove 'position: relative' from default CSS
  src/styl/imports/universal.styl
  src/styl/index.styl
Labels: :bug: bug

#209 Show pointer cursor
  src/styl/index.styl
Labels: enhancement

#212 Fix watch task
  gulpfile.js
Labels: :bug: bug, urgent

#205 Fix: Update HSTS policies to match listing requirements
  netlify.toml
Labels: enhancement

#220 Fix/js deps to body
  src/pug/index.pug
Labels: :bug: bug

#221 Update Selectr to v2.4.8
  src/pug/index.pug
Labels: enhancement

#222 Use jsDeliver instead of unpkg as CDN provider
  src/pug/includes/head.pug
  src/pug/index.pug
Labels: enhancement

#225 Non blocking fonts loading
  gulpfile.js
  package-lock.json
  package.json
  src/fonts/cabin-v12-latin-regular.woff
  src/fonts/cabin-v12-latin-regular.woff2
  src/img/logo.png
  src/pug/includes/head.pug
  src/styl/imports/base.styl
  src/styl/index.styl
Labels: enhancement

#226 Generate WebP images
  get-data.js
  gulpfile.js
  src/pug/includes/body.pug
Labels: enhancement

#232 added Alligator swag to data.json
  data.json
Labels: :tada: new swag
