Repository swapagarwal/swag-for-dev, pull requests merged in 2018-10, with the labels that each got.

#55 Add Microsoft Hacktoberfest t-shirt
  README.md
  data.json
Labels: enhancement

#65 Updated the Hacktoberfest t-shirt image
  README.md
  data.json
Labels: bug

#68 Add tooltip for difficulty indicators
  site/src/js/index.js
Labels: enhancement

#81 Update Microsoft's Hacktoberfest tshirt
  data.json
Labels: bug

#78 feat: Implement tag handling
  data.json
  site/src/js/index.js
  site/src/pug/includes/body.pug
  site/src/pug/includes/head.pug
  site/src/styl/imports/card.styl
  site/src/styl/imports/universal.styl
  site/src/styl/index.styl
Labels: enhancement

#83 Fix Website layout broken on mobile devices
  site/src/styl/index.styl
Labels: enhancement

#72 Website docs
  site/README.md
Labels: enhancement

#67 Added OpenEBS Hacktoberfest
  data.json
Labels: enhancement

#80 ✨Add Netlify Configuration
  netlify.toml
Labels: enhancement

#84 ✨ server side rendering
  site/gulpfile.js
  site/src/js/index.js
  site/src/pug/includes/body.pug
Labels: enhancement

#97 Fixes #96 Added data for Twilio swag.
  data.json
Labels: new-swag

#74 🎨 A11y Improvements to Site
  site/src/js/index.js
  site/src/pug/includes/body.pug
  site/src/styl/imports/a11y.styl
  site/src/styl/imports/card.styl
  site/src/styl/index.styl
Labels: enhancement

#107 fix issue #94
  site/gulpfile.js
Labels: bug

#58 Add WhatIsMyBrowser.com swag
  data.json
Labels: new-swag

#110 Adding Nexmo free T-Shirt for #Nextoberfest
  data.json
Labels: new-swag

#123 added clarification to nexmo offer
  data.json
Labels: bug

#132 Adding Passenger swag
  data.json
Labels: new-swag

#102 Add Umbraco swag
  data.json
Labels: new-swag

#111 Add LICENCE file
  LICENSE
Labels: enhancement

#128 Adding LBRY's hacktoberfest
  data.json
Labels: new-swag

#127 Adding source{d}'s hacktoberfest
  data.json
Labels: new-swag, urgent

#130 Adding OpenBazaar's HacktoberFest
  data.json
Labels: new-swag, urgent

#131 Adding Kong's contribution swag
  data.json
Labels: new-swag

#60 Add Gatsby
  data.json
Labels: new-swag

#135 Add Aras Swag opportunity
  data.json
Labels: new-swag

#141 add Add Operation Code Hacktoberfest swag
  data.json
Labels: new-swag, urgent
