Repository swapagarwal/swag-for-dev, pull requests merged in 2019-01, with the labels that each got.

#239 Add code tag style
  src/styl/imports/base.styl
Labels: enhancement

#235 Add SimbaChain swag
  data.json
Labels: :tada: new swag

#231 Make Selectr look like other select inputs
  src/js/index.js
  src/pug/includes/body.pug
  src/pug/includes/head.pug
  src/pug/index.pug
  src/styl/imports/selectr-theme.styl
  src/styl/index.styl
Labels: enhancement, 🎨 PR: UI/X Testing

#236 Add Contentful swag
  data.json
Labels: :tada: new swag

#248 Fix typos
  data.json
Labels: enhancement

#159 Create `expired` tag to mark expired promotions
  data.json
  get-data.js
  gulpfile.js
  src/js/index.js
  src/pug/includes/body.pug
  src/styl/index.styl
Labels: enhancement, 🎨 PR: UI/X Testing

#234 Add 7PHP Swag
  data.json
Labels: :tada: new swag, enhancement

#258 Add NativeScript swag
  data.json
Labels: :tada: new swag, enhancement

#256 Add JS Bin Swag (#184)
  data.json
Labels: :tada: new swag, enhancement
