Repository swapagarwal/swag-for-dev, pull requests merged in 2019-10, with the labels that each got.

#386 Add LBRY
  data.json
Labels: :sparkles: fix swag

#356 Update Hasura's swag for Hacktoberfest 2019
  data.json
Labels: :sparkles: fix swag

#348 Add Hacktoberfest 2019 - MayaData
  data.json
Labels: :tada: new swag

#342 Added Uno to Swags
  data.json
Labels: :tada: new swag

#202 HTTPS links
  README.md
Labels: enhancement, ⏱ needs Input

#355 Updated Operation Code Event for 2019
  data.json
Labels: :sparkles: fix swag

#361 Updated Squashtoberfest for 2019
  data.json
Labels: :sparkles: fix swag
